---

name: Publish Container
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  containers:
    name: Update container images
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lanl/bml
          tag_with_ref: true
